#pragma once

//#define PRINT_FUNC_NOT_FOUND_ERROR TRUE
//#define DISABLE_PRINTS FALSE
//
//#define KEYBOARD_TOGGLE_KEY VK_NUMPAD9
//#define CONTROLLER_TOGGLE_KEY_ACTION_1 INPUT_COVER
//#define CONTROLLER_TOGGLE_KEY_ACTION_2 INPUT_CONTEXT_A
